"""Initial schema: raw_items and pain_points

Revision ID: 7966ef7ed1a4
Revises:
Create Date: 2026-03-10 00:44:16.975178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7966ef7ed1a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pain_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pain_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avg_severity', sa.Float(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', 'type', name='uq_raw_item')
    )
    op.create_index(op.f('ix_raw_items_external_id'), 'raw_items', ['external_id'], unique=False)
    op.create_table('pain_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=False),
    sa.Column('is_b2b', sa.Boolean(), nullable=False),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pain_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pain_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_workaround', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity_1_to_10', sa.Integer(), nullable=True),
    sa.Column('willingness_to_pay_signal', sa.Boolean(), nullable=False),
    sa.Column('mentions_tool_names', sa.JSON(), nullable=True),
    sa.Column('saas_opportunity_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_called_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_item_id')
    )
    op.create_index(op.f('ix_pain_points_is_b2b'), 'pain_points', ['is_b2b'], unique=False)
    op.create_index(op.f('ix_pain_points_pain_category'), 'pain_points', ['pain_category'], unique=False)
    op.create_index(op.f('ix_pain_points_severity_1_to_10'), 'pain_points', ['severity_1_to_10'], unique=False)
    op.create_table('pain_cluster_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('pain_point_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['pain_clusters.id'], ),
    sa.ForeignKeyConstraint(['pain_point_id'], ['pain_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pain_cluster_items')
    op.drop_index(op.f('ix_pain_points_severity_1_to_10'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_pain_category'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_is_b2b'), table_name='pain_points')
    op.drop_table('pain_points')
    op.drop_index(op.f('ix_raw_items_external_id'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_table('communities')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('pain_clusters')
    # ### end Alembic commands ###
